workflows:
  android-capacitor-workflow:
    name: Kilogram Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      # This line fixes the 'invalid source release: 21' error
      java: 21 
      node: latest
      npm: latest
    scripts:
      - name: Install dependencies
        script: | 
          npm install
      - name: Build Web Project
        script: | 
          npm run build
      - name: Update Capacitor Android
        script: | 
          npx cap sync android
      - name: Build Android APK
        script: | 
          cd android
          chmod +x gradlew 
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - sahilmeshram1917@gmail.com